[package]
name = "autopush_common"
version = "1.0.0"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[lib]
name = "autopush_common"

[dependencies]
cadence = "0.17.1"
chrono = "0.4.7"
config = "0.9.3"
error-chain = "0.12.1"
futures = "0.1.28"
futures-backoff = "0.1.0"
httparse = "1.3.4"
# XXX: pin to hyper 0.11 for now: 0.12 has many changes..
hyper = "0.11.27"
lazy_static = "1.3.0"
mozsvc-common = "0.1.1"
rand = "0.7.0"
regex = "1.2.0"
reqwest = "0.9.19"
rusoto_core = "0.40.0"
rusoto_credential = "0.40.0"
rusoto_dynamodb = "0.40.0"
sentry = { version = "0.15.5", features = ["with_error_chain"] }
serde = "1.0.97"
serde_derive = "1.0.97"
serde_dynamodb = "0.3.2"
serde_json = "1.0.40"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.3.0"
slog-term = "2.4.1"
slog-mozlog-json = "0.1.0"
slog-scope = "4.1.2"
slog-stdlog = "3.0.5"
tokio-core = "0.1.17"
tungstenite = { version = "0.8.1", default-features = false }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
