[package]
name = "autopush"
version = "1.54.1"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[[bin]]
name = "autopush_rs"
path = "src/main.rs"

[dependencies]
autopush_common = { path = "../autopush-common" }
base64 = "0.10.1"
bytes = "0.4.12"
cadence = "0.17.1"
chan-signal = "0.3.2"
config = "0.9.3"
docopt = "1.1.0"
error-chain = "0.12.1"
fernet = "0.1.0"
futures = "0.1.28"
hex = "0.3.2"
httparse = "1.3.4"
# XXX: pin to hyper 0.11 for now: 0.12 has many changes..
hyper = "0.11.27"
lazy_static = "1.3.0"
mozsvc-common = "0.1.1"
openssl = "0.10.24"
reqwest = "0.9.19"
rusoto_dynamodb = "0.40.0"
sentry = { version = "0.15.5", features = ["with_error_chain"] }
serde = "1.0.97"
serde_derive = "1.0.97"
serde_dynamodb = "0.3.2"
serde_json = "1.0.40"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.3.0"
slog-term = "2.4.1"
slog-mozlog-json = "0.1.0"
slog-scope = "4.1.2"
# state_machine_future = { version = "0.1.6", features = ["debug_code_generation"] }
state_machine_future = "0.2.0"
time = "0.1.42"
tokio-core = "0.1.17"
tokio-io = "0.1.12"
tokio-openssl = "0.3.0"
tokio-service = "0.1.0"
tokio-tungstenite = { version = "0.8.0", default-features = false }
tungstenite = { version = "0.8.1", default-features = false }
uuid = { version = "0.7.4", features = ["serde", "v4"] }
woothee = "0.10.0"
