[package]
name = "autopush"
version = "1.54.4"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]
edition = "2018"

[[bin]]
name = "autopush_rs"
path = "src/main.rs"

[dependencies]
autopush_common = { path = "../autopush-common" }
base64 = "0.11.0"
# XXX: pin to < 0.5 for hyper 0.11
bytes = "0.5"
cadence = "0.19.1"
crossbeam-channel = "0.4.2"
chrono = "0.4.10"
config = "0.10.1"
docopt = "1.1.0"
env_logger = "0.7.1"
error-chain = "0.12.2"
fernet = "0.1.3"
futures = { version = "0.3", features = ["compat"] }
hex = "0.4.2"
httparse = "1.3.4"
hyper = "0.13"
lazy_static = "1.4.0"
log = { version = "0.4.8", features = ["max_level_info", "release_max_level_info"] }
mozsvc-common = "0.1.1"
openssl = "0.10.28"
reqwest = "0.10"
rusoto_dynamodb = "0.42"
sentry = { version = "0.18.0", features = ["with_error_chain"] }
serde = "1.0.104"
serde_derive = "1.0.104"
serde_dynamodb = "0.4.1"
serde_json = "1.0.48"
signal-hook = "0.1.13"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.4.0"
slog-term = "2.5.0"
slog-mozlog-json = "0.1.0"
slog-scope = "4.3.0"
# state_machine_future = { version = "0.1.6", features = ["debug_code_generation"] }
state_machine_future = "0.2.0"
tokio = "0.2"
tokio-openssl = "0.4.0"
tower-service = "0.1.0"
tokio-tungstenite = { version = "0.10", default-features = false }
tungstenite = { version = "0.9.2", default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
woothee = "0.10.0"
